# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#Coffeeshop.destroy_all

coffeeshops = Coffeeshop.create([
    {
        name: "Alfred Coffee & Kitchen", 
        display_address: "8428 Melrose Place A",
        display_city:"Los Angeles", 
        display_state:"CA", 
        display_zip: "90069", 
        neighborhood: "Beverly Grove", 
        phone: "(323) 944-0811",
        fair_trade: true, 
        direct_trade: false,
        organic: false,
        url: "http://www.alfredcoffee.com/", 
        yelp_id: "alfred-coffee-and-kitchen-los-angeles", 
        yelp_rating:4.5, 
        yelp_review:161, 
        yelp_url:"http://www.yelp.com/biz/alfred-coffee-and-kitchen-los-angeles",
        latitude: 34.083366,
        longitude: -118.374309
    },
    {
        name: "Antigua Coffee", 
        display_address: "3400 N. Figueroa Street",
        display_city:"Los Angeles", 
        display_state:"CA", 
        display_zip: "90065",
        neighborhood: "Cypress Park", 
        phone: "(323) 539-2233",
        fair_trade: true, 
        direct_trade: false,
        organic: false,
        url: "http://www.antiguacoffeehouse.com", 
        yelp_id: "antigua-coffee-Los-Angeles",
        yelp_rating:4, 
        yelp_review:129, 
        yelp_url: "http://www.yelp.com/biz/antigua-coffee-los-angeles",
        latitude: 34.0874118,
        longitude: -118.217485
    },
    {
        name: 'Balconi Coffee Company', 
        display_address: '11301 West Olympic Boulevard', 
        display_city: 'Los Angeles', 
        display_state: 'CA', 
        display_zip: '90064', 
        neighborhood: 'Sawtelle',
        phone: '(310) 906-0267', 
        fair_trade: true, 
        organic: true, 
        direct_trade: nil,
        yelp_rating: 4.5, 
        yelp_review: 344,
        yelp_id: 'balconi-coffee-company-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/balconi-coffee-company-los-angeles',
        url: 'http://www.balconicoffeecompany.com/',
        latitude: 34.0380128,
        longitude: -118.4418103
    },
    {
        name: "Barista Society Coffee Boutique", 
        display_address: "633 West Fifth Street ",
        display_city:"Los Angeles", 
        display_state:"CA", 
        display_zip: "90071",
        neighborhood: "Downtown", 
        phone: "(213)444-3389",
        fair_trade: false, 
        direct_trade: true,
        organic: true,
        url: "http://www.baristasociety.com/", 
        yelp_id: "barista-society-coffee-boutique-los-angeles", 
        yelp_rating:5, 
        yelp_review:98, 
        yelp_url: "http://www.yelp.com/biz/barista-society-coffee-boutique-los-angeles",
        latitude: 34.051038,
        longitude: -118.254436
    },
    {
        name:"Black Dog Coffee", 
        display_address: "5657 Wilshire Blvd.", 
        display_city: "Los Angeles", 
        display_state: "CA", 
        display_zip: "90036", 
        neighborhood: "Mid-Wilshire", 
        phone: "(323) 933-1976",
        fair_trade: true, 
        direct_trade: false,
        organic: false,
        url:"http://blackdogcoffee.com", 
        yelp_id:"black-dog-coffee-los-angeles", 
        yelp_rating: 3.5, 
        yelp_review:155,
        yelp_url:"http://www.yelp.com/biz/black-dog-coffee-los-angeles",
        latitude: 34.062765,
        longitude: -118.35187
    },
    {
        name: "Bourbon Street Cafe", 
        display_address: "698 S. VERMONT AVE. #103",
        display_city:"Los Angeles", 
        display_state:"CA", 
        display_zip: "90005", 
        neighborhood: "Koreatown", 
        phone: "(213)388-7888",
        fair_trade: true, 
        direct_trade: false,
        organic: false,
        url: "http://bourbonstcafe.squarespace.com/", 
        yelp_id: "bourbon-street-cafe-los-angeles", 
        yelp_rating:4, 
        yelp_review:207, 
        yelp_url: "http://www.yelp.com/biz/bourbon-street-cafe-los-angeles",
        latitude: 34.060116,
        longitude: -118.291278
    },
    {
        name: "Bourgeois Pig", 
        display_address: "5931 Franklin Ave.",
        display_city:"Los Angeles", 
        display_state:"CA", 
        display_zip: "90028",
        neighborhood: 'Hollywood Hills', 
        phone: '(323) 464-6008', 
        fair_trade: false, 
        direct_trade: false,
        organic: true,
        url: "http://www.bourgeoispig.menutoeat.com", 
        yelp_id: "bourgeois-pig-los-angeles", 
        yelp_rating:4, 
        yelp_review:437, 
        yelp_url: "http://www.yelp.com/biz/bourgeois-pig-los-angeles",
        latitude: 34.1053735,
        longitude: -118.3190009
    },
    {
        name: "Bru Coffee Bar", 
        display_address: "1866 n vermont avenue",
        display_city:"Los Angeles", 
        display_state:"CA", 
        display_zip: "90027",
        neighborhood: 'Loz Feliz', 
        phone: '(323) 664-7500', 
        fair_trade: false, 
        direct_trade: true,
        organic: true,
        url: "http://www.brucoffeebar.com", 
        yelp_id: "bru-coffeebar-los-angeles-2", 
        yelp_rating:3.5, 
        yelp_review:174, 
        yelp_url:"http://www.yelp.com/biz/bru-coffeebar-los-angeles-2",
        latitude: 34.104947,
        longitude: -118.2915327
    },
    {
        name: "Brew/Well", 
        display_address: " 3525 West 8th Street, Suite 101",
        display_city:"Los Angeles", 
        display_state:"CA", 
        display_zip: "90005",
        neighborhood: 'Koreatown', 
        phone: '(213) 384-0884', 
        fair_trade: false, 
        direct_trade: true,
        organic: true,
        url: "https://www.facebook.com/BrewWellCoffee", 
        yelp_id: "brewwell-los-angeles", 
        yelp_rating:4.5, 
        yelp_review:115, 
        yelp_url:"http://www.yelp.com/biz/brewwell-los-angeles",
        latitude: 34.0580418,
        longitude: -118.3071801
    },
    {
        name: "Cacao Coffee House", 
        display_address: "11609 Santa Monica",
        display_city:"Los Angeles", 
        display_state:"CA", 
        display_zip: "90025",
        neighborhood: 'Sawtelle', 
        phone: '(310) 473-7283', 
        fair_trade: false, 
        direct_trade: false,
        organic: true,
        url: "http://www.cacaocoffeehouse.com", 
        yelp_id: "cacao-coffee-house-los-angeles", 
        yelp_rating:3.5, 
        yelp_review:135, 
        yelp_url:"http://www.yelp.com/biz/cacao-coffee-house-los-angeles",
        latitude: 34.0446,
        longitude: -118.4541679
    },
    {
        name: "Cafe De Leche", 
        display_address: "5000 York Blvd.",
        display_city:"Los Angeles", 
        display_state:"CA", 
        display_zip: "90042",
        neighborhood: 'Highland Park', 
        phone: '(323)551-6828', 
        fair_trade: false, 
        direct_trade: true,
        organic: true,
        url: "http://www.cafedeleche.net", 
        yelp_id: "caf%C3%A9-de-leche-los-angeles-2", 
        yelp_rating:4, 
        yelp_review:289, 
        yelp_url:"http://www.yelp.com/biz/caf%C3%A9-de-leche-los-angeles-2",
        latitude: 34.1214403,
        longitude: -118.2068745
    },
    {
        name: "Cafe Demitasse", 
        display_address: "135 S San Pedro St",
        display_city:"Los Angeles", 
        display_state:"CA", 
        display_zip: "90012",
        neighborhood: 'Little Toyko', 
        phone: '(213) 613-9300', 
        fair_trade: nil, 
        organic: nil,
        direct_trade: true,
        yelp_rating: 4.0, 
        yelp_review: 447, 
        yelp_id: "demitasse-los-angeles", 
        yelp_url:"http://www.yelp.com/biz/demitasse-los-angeles",
        url: "http://cafedemitasse.com/",
        latitude: 34.0498402,
        longitude: -118.2413833
    },
    {
        name: "Cafe Demitasse", 
        display_address: "1149 3rd St",
        display_city:"Santa Monica", 
        display_state:"CA", 
        display_zip: "90403",
        neighborhood: 'Santa Monica', 
        phone: '(310) 260-6308', 
        fair_trade: nil, 
        organic: nil,
        direct_trade: true,
        yelp_rating: 4.0, 
        yelp_review: 89, 
        yelp_id: "demitasse-santa-monica-santa-monica", 
        yelp_url:"http://www.yelp.com/biz/demitasse-santa-monica-santa-monica",
        url: "http://cafedemitasse.com/",
        latitude: 34.0188173,
        longitude: -118.499444
    },
    {
        name:"Cafe Dulce", 
        display_address: "134 Japanese Village Plaza Bldg. E", 
        display_city: "Los Angeles", 
        display_state: "Ca", 
        display_zip: "90266", 
        neighborhood: "Little Toyko", 
        phone: "(213) 346-9910",
        fair_trade: false,
        direct_trade: false,
        organic: true,
        url:"http://www.cafedulce.com", 
        yelp_id:"cafe-dulce-los-angeles", 
        yelp_rating:4, 
        yelp_review: 870,
        yelp_url: "http://www.yelp.com/biz/cafe-dulce-los-angeles",
        latitude: 34.0490563,
        longitude: -118.2399017
    },
    {
        name: 'Caffe Luxxe', 
        display_address: '11975 San Vicente Blvd', 
        display_city: 'Los Angeles', 
        display_state: 'CA', 
        display_zip: '90049',
        neighborhood: 'Brentwood', 
        phone: '(310) 394-2222',
        fair_trade: nil,
        organic: nil, 
        direct_trade: true, 
        yelp_rating: 4.0, 
        yelp_review: 94,
        yelp_id: 'caffe-luxxe-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/caffe-luxxe-los-angeles',
        url: 'http://www.caffeluxxe.com/',
        latitude: 34.0526081,
        longitude: -118.4718797
    },
    {
        name: 'Caffe Luxxe', 
        display_address: '925 Montana Ave', 
        display_city: 'Santa Monica', 
        display_state: 'CA', 
        display_zip: '90403', 
        neighborhood: 'Santa Monica',
        phone: '(310) 394-2222',
        fair_trade: nil,
        organic: nil, 
        direct_trade: true, 
        yelp_rating: 4.0, 
        yelp_review: 261,
        yelp_id: 'caffe-luxxe-santa-monica',
        yelp_url: 'http://http://www.yelp.com/biz/caffe-luxxe-santa-monica',
        url: 'http://www.caffeluxxe.com/',
        latitude: 34.029062,
        longitude: -118.4994033
    },
    {
        name: 'Caffe Luxxe', 
        display_address: '225 26th St.', 
        display_city: 'Santa Monica', 
        display_state: 'CA', 
        display_zip: '90402', 
        neighborhood: 'Brentwood',
        phone: '(310) 394-2222', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 4.0, 
        yelp_review: 41,
        yelp_id: 'caffe-luxxe-santa-monica-2',
        yelp_url: 'http://www.yelp.com/biz/caffe-luxxe-santa-monica-2',
        url: 'http://www.caffeluxxe.com/',
        latitude: 34.0475109,
        longitude: -118.4904307
    },
    {
        name: 'Cafecito Organico', 
        display_address: '2930 Bristol St. Ste B105', 
        display_city: 'Costa Mesa', 
        display_state: 'CA', 
        display_zip: '92626', 
        neighborhood: 'Costa Mesa',
        phone: '(714) 394-2222', 
        fair_trade: true,
        organic: true,
        direct_trade: nil, 
        yelp_rating: 4.0, 
        yelp_review: 88,
        yelp_id: 'cafecito-organico-santa-monica',
        yelp_url: 'http://www.yelp.com/biz/cafecito-organico-santa-monica',
        url: 'http://www.cafecitoorganico.com/',
        latitude: 33.6775633,
        longitude: -117.886193
    },
    {
        name: 'Coffee Commissary', 
        display_address: '3121 W Olive Ave', 
        display_city: 'Burbank', 
        display_state: 'CA', 
        display_zip: '91505',
        neighborhood: 'Burbank', 
        phone: '(818) 556-6055', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 3.5, 
        yelp_review: 90,
        yelp_id: 'coffee-commissary-burbank',
        yelp_url: 'http://www.yelp.com/biz/coffee-commissary-burbank',
        url: 'http://www.coffeecommissary.com/',
        latitude: 34.1560937,
        longitude: -118.3351648
    },
    {
        name: 'Coffee Commissary', 
        display_address: '801 N Fairfax Ave', 
        display_city: 'Los Angeles', 
        display_state: 'CA', 
        display_zip: '90046',
        neighborhood: 'Beverly Grove', 
        phone: '(323) 782-1465', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 4.0, 
        yelp_review: 345,
        yelp_id: 'coffee-commissary-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/coffee-commissary-los-angeles',
        url: 'http://www.coffeecommissary.com/',
        latitude: 34.0856597,
        longitude: -118.3617018
    },
    {
        name: 'Coffee Commissary', 
        display_address: '6087 W Sunset Blvd', 
        display_city: 'Los Angeles', 
        display_state: 'CA', 
        display_zip: '90028',
        neighborhood: 'Hollywood', 
        phone: nil, 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 4.0, 
        yelp_review: 16,
        yelp_id: 'coffee-commissary-los-angeles-2',
        yelp_url: 'http://www.yelp.com/biz/coffee-commissary-los-angeles-2',
        url: 'http://www.coffeecommissary.com/',
        latitude: 34.098346,
        longitude: -118.321765
    },
    {
        name: 'Cognoscenti', 
        display_address: '3156 Glendale Blvd', 
        display_city: 'Los Angeles', 
        display_state: 'CA', 
        display_zip: '90039',
        neighborhood: 'Atwater Village', 
        phone: '(323) 319-6459',
        fair_trade: nil,
        organic: nil, 
        direct_trade: true, 
        yelp_rating: 4.5, 
        yelp_review: 70,
        yelp_id: 'cognoscenti-coffee-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/cognoscenti-coffee-los-angeles',
        url: 'http://www.popupcoffee.com',
        latitude: 34.1169451,
        longitude: -118.261584
    },
    {
        name: 'Cognoscenti', 
        display_address: '6114 Washington Blvd', 
        display_city: 'Culver City', 
        display_state: 'CA', 
        display_zip: '90232',
        neighborhood: 'Culver City', 
        phone: '(310) 363-7325',
        fair_trade: nil,
        organic: nil, 
        direct_trade: true, 
        yelp_rating: 4.0, 
        yelp_review: 70,
        yelp_id: 'cognoscenti-coffee-culver-city-2',
        yelp_url: 'http://www.yelp.com/biz/cognoscenti-coffee-culver-city-2',
        url: 'http://www.popupcoffee.com',
        latitude: 34.0311017,
        longitude: -118.3778009
    },
    {
        name: 'Espresso Cielo', 
        display_address: '245 S Palm Canyon Dr', 
        display_city: 'Palm Springs', 
        display_state: 'CA', 
        display_zip: '92262', 
        neighborhood: 'Palm Springs',
        phone: '(760) 327-9050', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 4.5, 
        yelp_review: 136,
        yelp_id: 'espresso-cielo-palm-springs',
        yelp_url: 'http://www.yelp.com/biz/espresso-cielo-palm-springs',
        url: 'http://espressocielo.com/',
        latitude: 33.8204066,
        longitude: -116.5469791
    },
    {
        name: 'Espresso Cielo', 
        display_address: '3101 Main St', 
        display_city: 'Santa Monica', 
        display_state: 'CA', 
        display_zip: '90405',
        neighborhood: 'Santa Monica', 
        phone: '(310) 314-9999', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 4.0, 
        yelp_review: 150,
        yelp_id: 'espresso-cielo-santa-monica',
        yelp_url: 'http://www.yelp.com/biz/espresso-cielo-santa-monica',
        url: 'http://espressocielo.com/',
        latitude: 33.9980574,
        longitude: -118.4793631
    },
    {
        name: 'Espresso Profeta', 
        display_address: '1129 Glendon Avenue', 
        display_city: 'Los Angeles', 
        display_state: 'CA',
        display_zip: '90024', 
        neighborhood: 'Westwood, UCLA',
        phone: '(310) 208-3375', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 4.0, 
        yelp_review: 343,
        yelp_id: 'espresso-profeta-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/espresso-profeta-los-angeles',
        url: 'https://plus.google.com/115896672597873192051/about?gl=us&hl=en',
        latitude: 34.0602329,
        longitude: -118.444205
    },
    {
        name: 'G&B', 
        display_address: '324 S. Hill St., No. C19', 
        display_city: 'Los Angeles', 
        display_state: 'CA', 
        display_zip: '90013',
        neighborhood: 'Downtown', 
        phone: '(312) 555-5555', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 4.0, 
        yelp_review: 104,
        yelp_id: 'g-and-b-coffee-los-angeles-2',
        yelp_url: 'http://www.yelp.com/biz/g-and-b-coffee-los-angeles-2',
        url: 'http://gandbcoffee.com/',
        latitude: 34.05081,
        longitude: -118.249409
    },
    {
        name: 'Go Get Em Tiger', 
        display_address: '230 N Larchmont Blvd', 
        display_city: 'Los Angeles', 
        display_state: 'CA',
        display_zip: '90004', 
        neighborhood: 'Windsor Square',
        phone: '(213) 620-9668', 
        fair_trade: nil,
        organic: nil, 
        direct_trade: true,        
        yelp_rating: 4.0, 
        yelp_review: 84,
        yelp_id: 'go-get-em-tiger-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/go-get-em-tiger-los-angeles',
        url: 'http://ggetla.com/',
        latitude: 34.0755874,
        longitude: -118.3232999
    },
    {
        name: 'Groundworks', 
        display_address: '108 W 2nd St', 
        display_city: 'Los Angeles', 
        display_state: 'CA',
        display_zip: '90012', 
        neighborhood: 'Downtown',
        phone: '(213) 620-9668', 
        fair_trade: true,
        organic: true, 
        direct_trade: nil,        
        yelp_rating: 3.5, 
        yelp_review: 84,
        yelp_id: 'groundwork-coffee-co-los-angeles-4',
        yelp_url: 'http://www.yelp.com/biz/groundwork-coffee-co-los-angeles-4',
        url: 'http://www.groundworkcoffee.com/',
        latitude: 34.0510613,
        longitude: -118.244705
    },
    {
        name: 'Groundworks', 
        display_address: '1501 N Cahuenga Blvd', 
        display_city: 'Los Angeles', 
        display_state: 'CA',
        display_zip: '90028',
        neighborhood: 'Hollywood', 
        phone: '(323) 871-0143', 
        fair_trade: true,
        organic: true, 
        direct_trade: nil, 
        yelp_rating: 4.0, 
        yelp_review: 258,
        yelp_id: 'groundwork-coffee-company-los-angeles-7',
        yelp_url: 'http://www.yelp.com/biz/groundwork-coffee-company-los-angeles-7',
        url: 'http://www.groundworkcoffee.com/',
        latitude: 34.0981674,
        longitude: -118.3297713
    },
    {
        name: 'Groundworks', 
        display_address: '1601 Montana Ave', 
        display_city: 'Santa Monica', 
        display_state: 'CA',
        display_zip: '90403', 
        neighborhood: 'Santa Monica',
        phone: '(310) 899-9500', 
        fair_trade: true,
        organic: true, 
        direct_trade: nil, 
        yelp_rating: 3.5, 
        yelp_review: 27,
        yelp_id: 'groundwork-coffee-company-santa-monica-3',
        yelp_url: 'http://www.yelp.com/biz/groundwork-coffee-company-santa-monica-3',
        url: 'http://www.groundworkcoffee.com/',
        latitude: 34.0339824,
        longitude: -118.493368
    },
    {
        name: 'Groundworks', 
        display_address: '395 Santa Monica Pl', 
        display_city: 'Santa Monica', 
        display_state: 'CA',
        display_zip: '90401', 
        neighborhood: 'Santa Monica',
        phone: '(310) 458-3111', 
        fair_trade: true,
        organic: true, 
        direct_trade: nil, 
        yelp_rating: 4.0, 
        yelp_review: 58,
        yelp_id: 'groundwork-coffee-company-santa-monica-2',
        yelp_url: 'http://www.yelp.com/biz/groundwork-coffee-company-santa-monica-2',
        url: 'http://www.groundworkcoffee.com/',
        latitude: 34.0136367,
        longitude: -118.4937981
    },
    {
        name: 'Groundworks', 
        display_address: '2908 Main St', 
        display_city: 'Santa Monica', 
        display_state: 'CA',
        display_zip: '90403', 
        neighborhood: 'Santa Monica',
        phone: '(310) 452-8925', 
        fair_trade: true,
        organic: true, 
        direct_trade: nil, 
        yelp_rating: 4.0, 
        yelp_review: 69,
        yelp_id: 'groundwork-coffee-co-santa-monica-2',
        yelp_url: 'http://www.yelp.com/biz/groundwork-coffee-co-santa-monica-2',
        url: 'http://www.groundworkcoffee.com/',
        latitude: 33.9992577,
        longitude: -118.4811278
    },
    {
        name: 'Groundworks', 
        display_address: '3 Westminster Ave', 
        display_city: 'Venice', 
        display_state: 'CA',
        display_zip: '90291',
        neighborhood: 'Venice', 
        phone: '(310) 450-4540', 
        fair_trade: true,
        organic: true, 
        direct_trade: nil, 
        yelp_rating: 4.0, 
        yelp_review: 38,
        yelp_id: 'groundwork-coffee-company-venice-2',
        yelp_url: 'http://www.yelp.com/biz/groundwork-coffee-company-venice-2',
        url: 'http://www.groundworkcoffee.com/',
        latitude: 33.9885275,
        longitude: -118.4749576
    },
    {
        name: 'Groundworks', 
        display_address: '671 Rose Ave', 
        display_city: 'Venice', 
        display_state: 'CA',
        display_zip: '90291', 
        neighborhood: 'Venice',
        phone: '(310) 664-8830', 
        fair_trade: true,
        organic: true, 
        direct_trade: nil, 
        yelp_rating: 4.0, 
        yelp_review: 198,
        yelp_id: 'groundwork-coffee-company-venice-3',
        yelp_url: 'http://www.yelp.com/biz/groundwork-coffee-company-venice-3',
        url: 'http://www.groundworkcoffee.com/',
        latitude: 34.000374,
        longitude: -118.470273
    },
    {
        name: 'Handsome Coffee Roasters', 
        display_address: '582 Mateo St', 
        display_city: 'Los Angeles', 
        display_state: 'CA',
        display_zip: '90004', 
        neighborhood: 'Downtown',
        phone: '(213) 621-4194', 
        fair_trade: nil,
        organic: nil, 
        direct_trade: true,        
        yelp_rating: 3.5, 
        yelp_review: 398,
        yelp_id: 'handsome-coffee-roasters-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/handsome-coffee-roasters-los-angeles',
        url: 'http://www.handsomecoffee.com/',
        latitude: 34.038941,
        longitude: -118.232467
    },
    {
        name: 'Intelligentsia', 
        display_address: '3922 W Sunset Blvd', 
        display_city: 'Los Angeles', 
        display_state: 'CA', 
        display_zip: '90029', 
        neighborhood: 'Silver Lake',
        phone: '(323) 663-6173',
        fair_trade: nil,
        organic: nil, 
        direct_trade: true, 
        yelp_rating: 4.0, 
        yelp_review: 1191,
        yelp_id: 'intelligentsia-coffee-los-angeles-4',
        yelp_url: 'http://www.yelp.com/biz/intelligentsia-coffee-los-angeles-4',
        url: 'http://www.intelligentsiacoffee.com/location/silver-lake-coffeebar',
        latitude: 34.0920063,
        longitude: -118.2802493
    },
    {
        name: 'Intelligentsia', 
        display_address: '55 East Colorado Blvd.', 
        display_city: 'Pasadena', 
        display_state: 'CA', 
        display_zip: '91105',
        neighborhood: 'Pasadena', 
        phone: '(626) 578-1270', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 4.0, 
        yelp_review: 846,
        yelp_id: 'intelligentsia-coffee-pasadena',
        yelp_url: 'http://www.yelp.com/biz/intelligentsia-coffee-pasadena',
        url: 'http://www.intelligentsiacoffee.com/location/pasadena-cafe',
        latitude: 34.1459937,
        longitude: -118.1492766
    },
    {
        name: 'Intelligentsia', 
        display_address: '1331 Abbot Kinney Blvd', 
        display_city: 'Venice', 
        display_state: 'CA', 
        display_zip: '90291', 
        neighborhood: 'Venice',
        phone: '(310) 399-1233',
        fair_trade: nil,
        organic: nil, 
        direct_trade: true, 
        yelp_rating: 4.0, 
        yelp_review: 842,
        yelp_id: 'intelligentsia-coffee-venice-venice',
        yelp_url: 'http://www.yelp.com/biz/intelligentsia-coffee-venice-venice',
        url: 'http://www.intelligentsiacoffee.com/location/venice-coffeebar',
        latitude: 33.9910995,
        longitude: -118.4669014
    },
    {
        name: 'Jones Coffee Roasters', 
        display_address: '693 S. Raymond Ave.', 
        display_city: 'Pasadena', 
        display_state: 'CA', 
        display_zip: '91105', 
        neighborhood: 'Pasadena',
        phone: '(626) 564-9291',
        fair_trade: nil,
        organic: nil, 
        direct_trade: true,
        yelp_rating: 4.0,
        yelp_review: 449,
        yelp_id: 'jones-coffee-roasters-pasadena',
        yelp_url: 'http://www.yelp.com/biz/jones-coffee-roasters-pasadena', 
        url: 'http://www.thebestcoffee.com/',
        latitude: 34.1337886,
        longitude: -118.1492671
    },
    {
        name: 'Lamill', 
        display_address: '1636 Silver Lake Blvd', 
        display_city: 'Los Angeles', 
        display_state: 'CA', 
        display_zip: '90026', 
        neighborhood: 'Silver Lake',
        phone: '(323) 663-4441', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 3.5, 
        yelp_review: 996,
        yelp_id: 'lamill-coffee-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/lamill-coffee-los-angeles',
        url: 'https://lamillcoffee.com/',
        latitude: 34.0888606,
        longitude: -118.2686893
    },
    {
        name: 'Paper or Plastik', 
        display_address: '5772 West Pico Boulevard', 
        display_city: 'Los Angeles', 
        display_state: 'CA', 
        display_zip: '90019', 
        neighborhood: 'Mid-City',
        phone: '(323) 935-0268', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 3.5, 
        yelp_review: 381,
        yelp_id: 'paper-or-plastik-cafe-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/paper-or-plastik-cafe-los-angeles',
        url: 'http://www.paperorplastikcafe.com/',
        latitude: 34.0508251,
        longitude: -118.3644004
    },
    {
        name: 'Primo Passo Coffee', 
        display_address: '702 Montana Avenue', 
        display_city: 'Santa Monica', 
        display_state: 'CA', 
        display_zip: '90403',
        neighborhood: 'Santa Monica', 
        phone: '(310) 451-5900', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 3.5, 
        yelp_review: 110,
        yelp_id: 'primo-passo-coffee-co-santa-monica-4',
        yelp_url: 'http://www.yelp.com/biz/primo-passo-coffee-co-santa-monica-4',
        url: 'http://primopassocoffee.com/',
        latitude: 34.0267907,
        longitude: -118.5015204
    },
    {
        name: 'Red Bread', 
        display_address: '13322 W Washington Blvd', 
        display_city: 'Culver City', 
        display_state: 'CA', 
        display_zip: '90066',
        neighborhood: 'Culver City', 
        phone: '(424) 272-5752', 
        fair_trade: true,
        organic: true,
        direct_trade: nil, 
        yelp_rating: 4.0, 
        yelp_review: 32,
        yelp_id: 'red-bread-culver-city',
        yelp_url: 'http://www.yelp.com/biz/red-bread-culver-city',
        url: 'http://www.thebreadisred.com/',
        latitude: 33.9928231,
        longitude: -118.4426953
    },
    {
        name: 'Single Origin', 
        display_address: 'Farmers Market, 6333 West 3rd Street Stall #316', 
        display_city: 'Los Angeles', 
        display_state: 'CA', 
        display_zip: '90036', 
        neighborhood: 'Fairfax',
        phone: '(323) 761-7976', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 4.5, 
        yelp_review: 47,
        yelp_id: 'single-origin-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/single-origin-los-angeles',
        url: 'http://www.socoffeela.com/',
        latitude: 34.0664817,
        longitude: -118.3520389
    },
    {
        name: 'Spring for Coffee', 
        display_address: '548 S Spring St', 
        display_city: 'Los Angeles', 
        display_state: 'CA', 
        display_zip: '90013', 
        neighborhood: 'Downtown',
        phone: '(213) 228-0041', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 4.5, 
        yelp_review: 261,
        yelp_id: 'spring-for-coffee-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/spring-for-coffee-los-angeles',
        url: 'http://www.springforcoffee.com/',
        latitude: 34.045952,
        longitude: -118.250472
    },
    {
        name: 'The Refinery', 
        display_address: '413 Santa Monica Blvd', 
        display_city: 'Santa Monica', 
        display_state: 'CA',
        display_zip: '90401',
        neighborhood: 'Santa Monica', 
        phone: '(310) 986-2776',
        fair_trade: nil,
        organic: nil, 
        direct_trade: true,  
        yelp_rating: 4.0, 
        yelp_review: 129,
        yelp_id: 'the-refinery-santa-monica',
        yelp_url: 'http://www.yelp.com/biz/the-refinery-santa-monica',
        url: 'http://www.refineryconcept.com/'
    },
    {
        name: 'Tiago Espresso Bar and Kitchen', 
        display_address: '7080 Hollywood Blvd',
        display_city: 'Los Angeles', 
        display_state: 'CA',
        display_zip: '90028', 
        neighborhood: 'Hollywood',
        phone: '(323) 466-5600', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 3.5, 
        yelp_review: 193,
        yelp_id: 'tiago-espresso-bar-kitchen-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/tiago-espresso-bar-kitchen-los-angeles',
        url: 'http://tiagocoffee.com/',
        latitude: 34.1011481,
        longitude: -118.344414
    },
    {
        name: 'Two Guns Espresso', 
        display_address: '350 N Sepulveda Blvd, Ste 7',
        display_city: 'Manhattan Beach', 
        display_state: 'CA',
        display_zip: '90266', 
        neighborhood: 'Manhattan Beach',
        phone: '(310) 318-2537', 
        fair_trade: nil,
        organic: nil,
        direct_trade: true, 
        yelp_rating: 4.5, 
        yelp_review: 237,
        yelp_id: 'two-guns-espresso-manhattan-beach-2',
        yelp_url: 'http://www.yelp.com/biz/two-guns-espresso-manhattan-beach-2',
        url: 'http://www.twogunsespresso.com/',
        latitude: 33.8813611,
        longitude: -118.3955415
    },
    {
        name: 'Urth Caffe', 
        display_address: '267 S Beverly Dr', 
        display_city: 'Beverly Hills', 
        display_state: 'CA',
        display_zip: '90212', 
        neighborhood: 'Beverly Hills',
        phone: '(310) 205-9311',
        fair_trade: nil, 
        organic: true, 
        direct_trade: nil,
        yelp_rating: 4.0, 
        yelp_review: 990,
        yelp_id: 'urth-caffe-beverly-hills-3',
        yelp_url: 'http://www.yelp.com/biz/urth-caffe-beverly-hills-3',
        url: 'http://www.urthcaffe.com/',
        latitude: 34.0626419,
        longitude: -118.399434
    },
    {
        name: 'Urth Caffe', 
        display_address: '451 S Hewitt St', 
        display_city: 'Los Angeles', 
        display_state: 'CA',
        display_zip: '90013', 
        neighborhood: 'Arts District, Downtown',
        phone: '(213) 797-4534',
        fair_trade: nil, 
        organic: true, 
        direct_trade: nil,
        yelp_rating: 4.0, 
        yelp_review: 2338,
        yelp_id: 'urth-caffe-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/urth-caffe-los-angeles',
        url: 'http://www.urthcaffe.com/',
        latitude: 34.041974,
        longitude: -118.235426
    },
    {
        name: 'Urth Caffe', 
        display_address: '594 E Colorado Blvd', 
        display_city: 'Pasadena', 
        display_state: 'CA',
        display_zip: '91101', 
        neighborhood: 'Pasadena',
        phone: '(626) 844-4644', 
        fair_trade: nil,
        organic: true, 
        direct_trade: nil,
        yelp_rating: 3.5, 
        yelp_review: 439,
        yelp_id: 'urth-caffe-los-angeles',
        yelp_url: 'http://www.yelp.com/biz/urth-caff%C3%A9-pasadena-2',
        url: 'http://www.urthcaffe.com/',
        latitude: 34.1458586,
        longitude: -118.1381973
    },
    {
        name: 'Urth Caffe', 
        display_address: '2327 Main St', 
        display_city: 'Santa Monica', 
        display_state: 'CA',
        display_zip: '90405',
        neighborhood: 'Santa Monica', 
        phone: '(310) 314-7040',
        fair_trade: nil, 
        organic: true, 
        direct_trade: nil,
        yelp_rating: 4.0, 
        yelp_review: 1590,
        yelp_id: 'urth-caffe-santa-monica',
        yelp_url: 'http://www.yelp.com/biz/urth-caffe-santa-monica',
        url: 'http://www.urthcaffe.com/',
        latitude: 34.0043593,
        longitude: -118.4857728,
    },
    {
        name: 'Urth Caffe', 
        display_address: '8565 Melrose Ave', 
        display_city: 'West Hollywood', 
        display_state: 'CA',
        display_zip: '90069',
        neighborhood: 'West Hollywood', 
        phone: '(310) 659-0628',
        fair_trade: nil, 
        organic: true, 
        direct_trade: nil,
        yelp_rating: 4.0, 
        yelp_review: 1348,
        yelp_id: 'urth-caffe-west-hollywood',
        yelp_url: 'http://www.yelp.com/biz/urth-caffe-west-hollywood',
        url: 'http://www.urthcaffe.com/',
        latitude: 34.0821163,
        longitude: -118.378866,
    }
])







