require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoffeeshopsController do
  #let!(:coffeeshop) { FactoryGirl.create :coffeeshop }
  # This should return the minimal set of attributes required to create a valid
  # Coffeeshop. As you add validations to Coffeeshop, be sure to
  # adjust the attributes here as well.
  #let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoffeeshopsController. Be sure to keep this updated too.
  #let(:valid_session) { {} }

  describe "GET index" do
      before(:each) do
        @coffeeshop1 = FactoryGirl.create(:coffeeshop, name: 'A', display_address: '324 S Hill St', display_city: 'Los Angeles', display_state: 'CA', display_zip: '90013')
        @coffeeshop2 = FactoryGirl.create(:coffeeshop, name: 'B', display_address: '451 S Hewitt St', display_city: 'Los Angeles', display_state: 'CA', display_zip: '90013')
      end

      it 'populates an array of coffeeshops' do 
        get :index
        assigns(:coffeeshops).should == [@coffeeshop1, @coffeeshop2]
      end
  end

  describe "GET show" do
    it "assigns the requested coffeeshop as @coffeeshop" do
      coffeeshop = FactoryGirl.create(coffeeshop) 
      get :show, {:id => coffeeshop.to_param}, valid_session
      assigns(:coffeeshop).should eq(coffeeshop)
    end
  end

  describe "GET new" do
    it "assigns a new coffeeshop as @coffeeshop" do
      get :new, {}, valid_session
      assigns(:coffeeshop).should be_a_new(Coffeeshop)
    end
  end

  describe "GET edit" do
    it "assigns the requested coffeeshop as @coffeeshop" do
      coffeeshop = Coffeeshop.create! valid_attributes
      get :edit, {:id => coffeeshop.to_param}, valid_session
      assigns(:coffeeshop).should eq(coffeeshop)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Coffeeshop" do
        expect {
          post :create, {:coffeeshop => valid_attributes}, valid_session
        }.to change(Coffeeshop, :count).by(1)
      end

      it "assigns a newly created coffeeshop as @coffeeshop" do
        post :create, {:coffeeshop => valid_attributes}, valid_session
        assigns(:coffeeshop).should be_a(Coffeeshop)
        assigns(:coffeeshop).should be_persisted
      end

      it "redirects to the created coffeeshop" do
        post :create, {:coffeeshop => valid_attributes}, valid_session
        response.should redirect_to(Coffeeshop.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coffeeshop as @coffeeshop" do
        # Trigger the behavior that occurs when invalid params are submitted
        Coffeeshop.any_instance.stub(:save).and_return(false)
        post :create, {:coffeeshop => { "name" => "invalid value" }}, valid_session
        assigns(:coffeeshop).should be_a_new(Coffeeshop)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Coffeeshop.any_instance.stub(:save).and_return(false)
        post :create, {:coffeeshop => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coffeeshop" do
        coffeeshop = Coffeeshop.create! valid_attributes
        # Assuming there are no other coffeeshops in the database, this
        # specifies that the Coffeeshop created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Coffeeshop.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => coffeeshop.to_param, :coffeeshop => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested coffeeshop as @coffeeshop" do
        coffeeshop = Coffeeshop.create! valid_attributes
        put :update, {:id => coffeeshop.to_param, :coffeeshop => valid_attributes}, valid_session
        assigns(:coffeeshop).should eq(coffeeshop)
      end

      it "redirects to the coffeeshop" do
        coffeeshop = Coffeeshop.create! valid_attributes
        put :update, {:id => coffeeshop.to_param, :coffeeshop => valid_attributes}, valid_session
        response.should redirect_to(coffeeshop)
      end
    end

    describe "with invalid params" do
      it "assigns the coffeeshop as @coffeeshop" do
        coffeeshop = Coffeeshop.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Coffeeshop.any_instance.stub(:save).and_return(false)
        put :update, {:id => coffeeshop.to_param, :coffeeshop => { "name" => "invalid value" }}, valid_session
        assigns(:coffeeshop).should eq(coffeeshop)
      end

      it "re-renders the 'edit' template" do
        coffeeshop = Coffeeshop.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Coffeeshop.any_instance.stub(:save).and_return(false)
        put :update, {:id => coffeeshop.to_param, :coffeeshop => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coffeeshop" do
      coffeeshop = Coffeeshop.create! valid_attributes
      expect {
        delete :destroy, {:id => coffeeshop.to_param}, valid_session
      }.to change(Coffeeshop, :count).by(-1)
    end

    it "redirects to the coffeeshops list" do
      coffeeshop = Coffeeshop.create! valid_attributes
      delete :destroy, {:id => coffeeshop.to_param}, valid_session
      response.should redirect_to(coffeeshops_url)
    end
  end

end
